// Generated by scripts/sync-surface.mjs from openclaw 2026.9.7. Do not edit by hand.
import { runKitchenHook } from "./scenarios.js";

export function registerAllHooks(api) {
  api.on("after_compaction", kitchenSinkSyncHook("after_compaction"));
  api.on("after_tool_call", kitchenSinkSyncHook("after_tool_call"));
  api.on("agent_end", kitchenSinkSyncHook("agent_end"));
  api.on("agent_turn_prepare", kitchenSinkSyncHook("agent_turn_prepare"));
  api.on("before_agent_finalize", kitchenSinkSyncHook("before_agent_finalize"));
  api.on("before_agent_reply", kitchenSinkSyncHook("before_agent_reply"));
  api.on("before_agent_run", kitchenSinkHook("before_agent_run"));
  api.on("before_compaction", kitchenSinkSyncHook("before_compaction"));
  api.on("before_dispatch", kitchenSinkSyncHook("before_dispatch"));
  api.on("before_install", kitchenSinkSyncHook("before_install"));
  api.on("before_message_write", kitchenSinkSyncHook("before_message_write"));
  api.on("before_model_resolve", kitchenSinkSyncHook("before_model_resolve"));
  api.on("before_prompt_build", kitchenSinkSyncHook("before_prompt_build"));
  api.on("before_reset", kitchenSinkSyncHook("before_reset"));
  api.on("before_tool_call", kitchenSinkSyncHook("before_tool_call"));
  api.on("channel_pairing_requested", kitchenSinkSyncHook("channel_pairing_requested"));
  api.on("cron_changed", kitchenSinkSyncHook("cron_changed"));
  api.on("cron_reconciled", kitchenSinkSyncHook("cron_reconciled"));
  api.on("gateway_start", kitchenSinkSyncHook("gateway_start"));
  api.on("gateway_stop", kitchenSinkSyncHook("gateway_stop"));
  api.on("heartbeat_prompt_contribution", kitchenSinkSyncHook("heartbeat_prompt_contribution"));
  api.on("inbound_claim", kitchenSinkSyncHook("inbound_claim"));
  api.on("llm_input", kitchenSinkSyncHook("llm_input"));
  api.on("llm_output", kitchenSinkSyncHook("llm_output"));
  api.on("message_received", kitchenSinkSyncHook("message_received"));
  api.on("message_sending", kitchenSinkSyncHook("message_sending"));
  api.on("message_sent", kitchenSinkSyncHook("message_sent"));
  api.on("model_call_ended", kitchenSinkSyncHook("model_call_ended"));
  api.on("model_call_started", kitchenSinkSyncHook("model_call_started"));
  api.on("reply_dispatch", kitchenSinkSyncHook("reply_dispatch"));
  api.on("reply_payload_sending", kitchenSinkSyncHook("reply_payload_sending"));
  api.on("resolve_exec_env", kitchenSinkSyncHook("resolve_exec_env"));
  api.on("session_end", kitchenSinkSyncHook("session_end"));
  api.on("session_start", kitchenSinkSyncHook("session_start"));
  api.on("skill_changed", kitchenSinkSyncHook("skill_changed"));
  api.on("skill_proposal_changed", kitchenSinkSyncHook("skill_proposal_changed"));
  api.on("skill_proposal_evaluate", kitchenSinkSyncHook("skill_proposal_evaluate"));
  api.on("subagent_delivery_target", kitchenSinkSyncHook("subagent_delivery_target"));
  api.on("subagent_ended", kitchenSinkSyncHook("subagent_ended"));
  api.on("subagent_progress", kitchenSinkSyncHook("subagent_progress"));
  api.on("subagent_spawned", kitchenSinkSyncHook("subagent_spawned"));
  api.on("tool_result_persist", kitchenSinkSyncHook("tool_result_persist"));
}

function kitchenSinkHook(name) {
  return async (event, context) => runKitchenHook(name, event, context);
}

function kitchenSinkSyncHook(name) {
  return (event, context) => runKitchenHook(name, event, context);
}
