// Generated by scripts/sync-surface.mjs from openclaw 2026.5.6. Do not edit by hand.
import { observeKitchenHook } from "./scenarios.js";

export function registerAllHooks(api) {
  api.on("after_compaction", kitchenSinkHook("after_compaction"));
  api.on("after_tool_call", kitchenSinkHook("after_tool_call"));
  api.on("agent_end", kitchenSinkHook("agent_end"));
  api.on("agent_turn_prepare", kitchenSinkHook("agent_turn_prepare"));
  api.on("before_agent_finalize", kitchenSinkHook("before_agent_finalize"));
  api.on("before_agent_reply", kitchenSinkHook("before_agent_reply"));
  api.on("before_agent_start", kitchenSinkHook("before_agent_start"));
  api.on("before_compaction", kitchenSinkHook("before_compaction"));
  api.on("before_dispatch", kitchenSinkHook("before_dispatch"));
  api.on("before_install", kitchenSinkHook("before_install"));
  api.on("before_message_write", kitchenSinkHook("before_message_write"));
  api.on("before_model_resolve", kitchenSinkHook("before_model_resolve"));
  api.on("before_prompt_build", kitchenSinkHook("before_prompt_build"));
  api.on("before_reset", kitchenSinkHook("before_reset"));
  api.on("before_tool_call", kitchenSinkHook("before_tool_call"));
  api.on("cron_changed", kitchenSinkHook("cron_changed"));
  api.on("gateway_start", kitchenSinkHook("gateway_start"));
  api.on("gateway_stop", kitchenSinkHook("gateway_stop"));
  api.on("heartbeat_prompt_contribution", kitchenSinkHook("heartbeat_prompt_contribution"));
  api.on("inbound_claim", kitchenSinkHook("inbound_claim"));
  api.on("llm_input", kitchenSinkHook("llm_input"));
  api.on("llm_output", kitchenSinkHook("llm_output"));
  api.on("message_received", kitchenSinkHook("message_received"));
  api.on("message_sending", kitchenSinkHook("message_sending"));
  api.on("message_sent", kitchenSinkHook("message_sent"));
  api.on("model_call_ended", kitchenSinkHook("model_call_ended"));
  api.on("model_call_started", kitchenSinkHook("model_call_started"));
  api.on("reply_dispatch", kitchenSinkHook("reply_dispatch"));
  api.on("session_end", kitchenSinkHook("session_end"));
  api.on("session_start", kitchenSinkHook("session_start"));
  api.on("subagent_delivery_target", kitchenSinkHook("subagent_delivery_target"));
  api.on("subagent_ended", kitchenSinkHook("subagent_ended"));
  api.on("subagent_spawned", kitchenSinkHook("subagent_spawned"));
  api.on("subagent_spawning", kitchenSinkHook("subagent_spawning"));
  api.on("tool_result_persist", kitchenSinkHook("tool_result_persist"));
}

function kitchenSinkHook(name) {
  return async (event, context) => observeKitchenHook(name, event, context);
}
